### PR TITLE
added MonthViewPagerDataSetObserver to refresh when needed

### LINKED ISSUE #20: FlexibleCalendar.refresh() doesn't use EventDataProvider.getEventsForTheDay() with Support Library 23.2
After upgrading to support library 23.2, it has stopped refreshing the correct display after:

- month page event
- fetch remote data
- remote data comes back
- call `FlexibleCalendar.refresh()` or `invalidate()`
- `EventDataProvider.getEventsForTheDay()` no longer called

It refreshes correctly once you select a date by clicking on it.

### PR DESCRIPTION
**Pull request by twig**
Closes #20

### CODE REVIEW

**Comment by p-v** [comment]
@twig Thanks for your interest but it does seem to work when you are on the same month for which you want to add more events.

**Comment by twig** [comment]
Hey @p-v, I'll link a working example which shows the FlexibleCalendar.refresh() call not working (first button) UNTIL the adapter notify methods are called manually (second button).

**Comment by twig** [comment]
You can find it here: https://github.com/twig/FlexibleCalendarTest

**Comment by twig** [comment]
It was tested on Android 4.1.1 but reproducible on 5.1 as well.

**Comment by p-v** [comment]
Yes that works. :+1: 

The only problem is if I keep adding the events they are no more aligned.

**Comment by twig** [comment]
Alignment isn't the problem I'm trying to solve here.

So your FlexibleCalendar.refresh() call works? Because on Genymotion and my phone it doesn't.

**Comment by twig** [comment]
For me, line 64 does nothing.

https://github.com/twig/FlexibleCalendarTest/blob/master/app/src/main/java/twig/flexiblecalendartest/MainActivityFragment.java#L55

**Comment by p-v** [comment]
It doesn't do anything for me as well but this fix is introducing alignment issues even if I'm using support library < 23.

**Comment by twig** [comment]
Can you show me where the alignment issue is broken so I can take a look at it?

**Comment by p-v** [comment]
@twig My bad. It works. I picked up some other commits from a different branch that created the issue. I'll merge this pr. FYI, everything works fine till version 23.1.1 but 23.2.0 has broken the library. Will have to fix several issues. Also I'm marking the library as *broken* for 23.2.0 in the README. 

Thanks for your contribution. :+1:

**Comment by p-v** [comment]
I'm not creating a release for this right now. Will do it once we fix all the issues.

**Comment by twig** [comment]
Cool thanks!

I understand. 23.2 has been quite buggy and I can still use my forked branch for compilation for the time being.

**Pull request merged**
