### PR TITLE
Added more functions in CalendarView

### PR DESCRIPTION
**Pull request by zhanhui913**
1) Added functions in FlexibleCalendarHelper that retrieves the year, month, and date value of a date.
2) Added function in FlexibleCalendar that moves the calendar view to a specified month.
3) Added another function in FlexibleCalendar that sets the selected date to specified date.

### CODE REVIEW

**Comment by p-v** [comment]
@zhanhui913 Thanks for the pr. 

For point **2**, it would be great if you can call `selectDate(int newYear, int newMonth, int newDay)` internally from the method `goToMonth()`. 

For **3**, apologies for not documenting it properly. There is already a method call `selectDate()` which accepts `Date` type.

**Comment by zhanhui913** [comment]
@p-v 
Thanks for the pointers:
I will remove the function for **3** and add those calls internally for **2**

**Comment by p-v** [comment]
@zhanhui913 A thought just creeped in. Isn't `goToMonth()` kind of ambiguous? Also, we are passing a `Date` type to it, which means it will have day, month and year, which in turns makes it the same thing as `selectDate(Date date)`. My bad, I missed it in the last comment.

**Comment by zhanhui913** [comment]
You're absolutely right, I wonder why I didnt think of that.
Thanks so much for reviewing the pull request.
Please ignore this pull. 
PS: really enjoy using this project btw.

**Comment by p-v** [comment]
You are welcome @zhanhui913.  Thank you for showing interest in the project. There are plenty of issues to be fixed and improvements needed. Pull requests are always welcome :smiley:

**Pull request closed without merging**
