### PR TITLE
Updating project

### PR DESCRIPTION
**Pull request by pedrofsn**

### CODE REVIEW

**Comment by p-v** [comment]
@pedrofsn Thanks for your efforts. I'll review and merge.

**Comment by p-v** [comment]
Can you please squash your commits to 'updating gradle' and 'refactoring/reorganizing'?

**Comment by pedrofsn** [comment]
It's done.

**Comment by pedrofsn** [comment]
Hi @p-v, can you accept my pull request?

**Comment by p-v** [comment]
Wasn't active lately. Thanks for the contribution.

**Pull request merged**
